ci: added e2e-test-summary step
The reason for this change is that this way this step can be required to pass for a PR to merge, which will indirectly require that all parallelized e2e tests jobs passed.

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -280,6 +280,17 @@ jobs:
           install: false
           spec: ${{ matrix.chunk.paths }}
 
+  e2e-test-summary:
+    name: E2E Tests Summary
+    runs-on: ubuntu-latest
+    needs: run-e2e-tests
+    if: ${{ always() }}
+    steps:
+      - run: |
+          if [[ "${{ needs.*.result }}" =~ failure ]]; then
+            echo "Some e2e tests failed"; exit 1
+          fi
+
   Skip-Executions:
     name: Skip Build And Test
     needs: check-file-changes
